CREATE TABLE BBOARD (
	NUM NUMBER(5) PRIMARY KEY,
	PASS VARCHAR2(30),
	NAME VARCHAR2(30),
	EMAIL VARCHAR2(30),
	TITLE VARCHAR2(30),
	CONTENT VARCHAR2(1000),
	READCOUNT NUMBER(4) DEFAULT 0,
	WRITEDATE DATE DEFAULT SYSDATE
);

CREATE SEQUENCE BOARD_SEQ START WITH 1 INCREMENT BY 1;

INSERT INTO BBOARD(num, name, email, pass, title, content)
VALUES(BOARD_SEQ.NEXTVAL, '강승진', 'xeungjin@nate.com', '1234', '첫방문', '반갑습니다.');

SELECT * FROM BBOARD